# Generated by Django 4.2 on 2023-04-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_tag_user_name_user_role_user_surname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="surname",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
