# Generated by Django 4.2 on 2023-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_user_name_remove_user_surname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="unique_id",
            field=models.BigIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_to_finish",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
